### ISSUE TITLE
Version specifier '1' gives pre-release (if you opt in with `include-all-prereleases: true`)

### ISSUE THREAD

**Issue by carstenbauer** [julia-actions/setup-julia#283] opened 2024-09-20 10:28 UTC
AFAIU, the version specifier '1' should give that latest **stable** 1.x release, i.e. 1.10 at the point of writing this. However, it doesn't but it currently gives the pre-release 1.11-rc3, see [here](https://github.com/JuliaFolds2/ChunkSplitters.jl/actions/runs/10956612974/job/30423024061?pr=48#step:3:12).

Related discussion on discourse: https://discourse.julialang.org/t/with-julia-actions-setup-julia-you-can-now-specify-lts-and-pre-named-versions/116281/7?u=carstenbauer

**Comment by DilumAluthge** [comment] 2024-09-20 10:48
It looks like you explicitly set `include-all-prereleases: true`. So that's the expected behavior, right?

**Comment by DilumAluthge** [comment] 2024-09-20 10:48
https://github.com/JuliaFolds2/ChunkSplitters.jl/blob/3b09fd001a40a5209e5520cfef13c7f74b14934d/.github/workflows/ci.yml#L30

**Comment by DilumAluthge** [comment] 2024-09-20 10:52
If you don't explicitly provide the value for `include-all-prereleases`, it will default to `include-all-prereleases: false`, and you won't get pre-releases.

**Comment by DilumAluthge** [comment] 2024-09-20 10:54
I'll close this, but if you can reproduce the behavior when you set `include-all-prereleases: false`, then let me know, and I'll reopen this.

**Closed by DilumAluthge** 2024-09-20 10:54 UTC
Labels: invalid

**Comment by carstenbauer** [comment] 2024-09-20 11:02
Oh... My bad and sorry for the noise.

**Comment by DilumAluthge** [comment] 2024-09-20 11:05
No worries!

**Comment by DilumAluthge** [comment] 2024-09-20 11:06
We could consider printing an extra log message to the CI log when `include-all-prereleases: true`, to make this kind of situation easier to spot.
